sudo: false
dist: trusty
language: go
go:
    - 1.7.x
install:
    - go get github.com/jehiah/go-strftime
    - go get github.com/ogier/pflag
    - go build tlog.go
script:
    "{ echo first line; sleep .5; echo second line; } | ./tlog"
notifications:
    email: false
